INSERT INTO votable(memetext, type) VALUES ('Bundtekst', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Wide', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('is gamergay', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Obamanite', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('is it?=', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('qwe', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('bassemand', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('qw', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Mads', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Består gymnasiet', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('numdget', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Hæng mig', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Tuomas', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Mine nødder brænder', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('NAMME :)', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('﷽﷽﷽﷽', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('nudles', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Farmand', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Thicc', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('suppe', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES (' (⁄ʘ⁄ ⁄ ω⁄ ⁄ ʘ⁄)♡ what dis', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('voldtægt', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('is okay', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('I´ve been kidnapped', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('the toasterbath', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('hmm', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('ligma', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('omega destroyer', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('stor hjerne', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES (',̷̢̦̱̼̩̼̳͚͈̩̭̀̈́̉̈́̋̽̍-̶͎̂͂̂̀̉̊́͋͂̏̓.̷̢̡̛̪̖͖̻̜͙̩̘̹̟̙̌̿͑͆̏̒,̷̧̘̟̤̭̼̤̍̔̑̋̈́̔̈́̕͝-̷̺͙̠̽̈́̇͑͂̐͊̌̆̀̕̚.̴̢̳͈̥̼̤̠̟̽̆̽͒̀̔͐͜,̸̼̖̪͇̪͇͓͉̲̞̲̰͙͒͒̃̔͊̓͒̈́͊̈́̑̑͜͝͝-̴̺̭̘̩̩͔̭̲͓̦̬̃̈͛͜.̵̢̛̘̺̱̬̠͉̳͎̹̩̖̫̹̼̄̔̅́̑͠,̸̛̛͓̣̰̳̹̟͈̹͈̤͍̟̺͊͊̇̔̃͒̎̕-̴̡̥̣̗̦̃͗͒ͅ.̷̛̭͚̼̯̩̼̂̈́͛̎,̸̡̬̦̦͙̜̳̈̌͛͒͜-̸̜̬̤̞̳̤̌̈̾͛̆͒̂͗̀.̶̨̬͚̪̪͕̞͇̯͉̖͈̀̎̀̽̐̈͊̿̈̉̿,̸̡͚͓̣̞̞͓̰̟̻͍̰̠̌̍̓̎̆́́̔̿̇̚-̵͓͙͈̭̮͖̟̗̗̬̗̪̫͕̏̃.̶͍̼̗̟̱͙̝̎͌͂̿̅͋͊̍̑̐̚͝,̴̢̈́̈́͑̈̊̏̀̏̏͒͐͒͝-̷̛̗̜͍̥̳̺̳̼̪͙̲̯̜̟͋̉͐̐̈́͑͜.̵̛̳̳̫̫͍̰̱̗͈̀̆̌̀̌͋̆̅͒̑̂͠͝,̷̛̙͖͓̩͓͉͍̲̪͚̱͈͉̹͋̋̉̀͊͐̒̃͝', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Dumpap', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('dyb', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('du nødder', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('furry master', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('den store svampemand', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('guden over helvedet', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('cash money', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('unyielding rage', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('party hard', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('[REDACTED]', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('how', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('shideded', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('faldende livskvalitet', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('selvmordstid', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('træt af livet', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('lille hjerne', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Jeg skider kærnemælk', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('HOREUNGE', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('selvmordstanker', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('kigger efter småbørn', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('stort lem', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Jeg skal pensioneres omgående', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('SPRØJTER', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('y´know', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('fortnitre?', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('affyret majskanonen', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('jeg har skidt i bukserne', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('jeff', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('plz respond', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('racermaven stopper aldrig', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES (':flushed:', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('heysan', 'MemeBottomtext');
INSERT INTO votable(memetext, type) VALUES ('Tag dit tøj af', 'MemeBottomtext');

INSERT INTO votable(memetext, type) VALUES ('Gamer kage', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Finally', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('29', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('When Mads', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('When you', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('qwe', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Fuck', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Coppercap', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('when', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Jeg tror', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Når', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Jeg har testikelkræft', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('D OGHOT', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('lille lort', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('When hjalte', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Formand', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('👀', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Lave', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('◕w◕', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Tid til', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Please help me', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('I have', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('hmm', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('your wish is', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('når thots er', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES (',̷̢̦̱̼̩̼̳͚͈̩̭̀̈́̉̈́̋̽̍-̶͎̂͂̂̀̉̊́͋͂̏̓.̷̢̡̛̪̖͖̻̜͙̩̘̹̟̙̌̿͑͆̏̒,̷̧̘̟̤̭̼̤̍̔̑̋̈́̔̈́̕͝-̷̺͙̠̽̈́̇͑͂̐͊̌̆̀̕̚.̴̢̳͈̥̼̤̠̟̽̆̽͒̀̔͐͜,̸̼̖̪͇̪͇͓͉̲̞̲̰͙͒͒̃̔͊̓͒̈́͊̈́̑̑͜͝͝-̴̺̭̘̩̩͔̭̲͓̦̬̃̈͛͜.̵̢̛̘̺̱̬̠͉̳͎̹̩̖̫̹̼̄̔̅́̑͠,̸̛̛͓̣̰̳̹̟͈̹͈̤͍̟̺͊͊̇̔̃͒̎̕-̴̡̥̣̗̦̃͗͒ͅ.̷̛̭͚̼̯̩̼̂̈́͛̎,̸̡̬̦̦͙̜̳̈̌͛͒͜-̸̜̬̤̞̳̤̌̈̾͛̆͒̂͗̀.̶̨̬͚̪̪͕̞͇̯͉̖͈̀̎̀̽̐̈͊̿̈̉̿,̸̡͚͓̣̞̞͓̰̟̻͍̰̠̌̍̓̎̆́́̔̿̇̚-̵͓͙͈̭̮͖̟̗̗̬̗̪̫͕̏̃.̶͍̼̗̟̱͙̝̎͌͂̿̅͋͊̍̑̐̚͝,̴̢̈́̈́͑̈̊̏̀̏̏͒͐͒͝-̷̛̗̜͍̥̳̺̳̼̪͙̲̯̜̟͋̉͐̐̈́͑͜.̵̛̳̳̫̫͍̰̱̗͈̀̆̌̀̌͋̆̅͒̑̂͠͝,̷̛̙͖͓̩͓͉͍̲̪͚̱͈͉̹͋̋̉̀͊͐̒̃͝', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Wat u doing', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('rød', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('den almægtige', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('pas på', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('jeg er', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('du har begået', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('pure', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('tid til at', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('endelig', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('what', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('HOLe CRAP!!!!!!!', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('det er tid til', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('det er mig', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('vent hvad', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('stor mand', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('Splitte mine bramsejl', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('NO WAY', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('when your´e', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('OH MY GOD!!!!!!!!!!!!!', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('når man får', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('HAHAHA', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('ok gutter', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('jeff', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('i showed you my ram stickk', 'MemeToptext');
INSERT INTO votable(memetext, type) VALUES ('watup gamer', 'MemeToptext');
INSERT INTO votable(filename, type) VALUES ('cursed2.PNG', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('Untitled.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('20200914_171910.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('whydidievenmakethis.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('cursed2.PNG', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('zgfhjklhgfd.PNG', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('4k_alien.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('rat.ong.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('IMG_20200922_173502.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('IMG_20200922_173502.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('IMG_20200922_173502.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('118761001_1007077003097391_7745935732917232986_n.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('stickbug.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('000 robot.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('6d557a6d0845383b750d3ed785f6d511.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('stickbug.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('Anmærkning 2020-04-04 014638.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('4UL2DRl.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('AboutYeaLong.JPG', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('slim jim.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('MALDIVERNE.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('36961343_2008790819151132_3728162660970135552_n (1).jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('feelsgood.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('20884867_1917726818488974_351887955_n.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('Anmærkning 2020-04-22 123721.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('Anmærkning 2020-04-22 123759.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('Anmærkning 2020-04-30 223019.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('Anmærkning 2020-04-04 014803.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('27718209_1822724704424412_1154780756_n.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('simcorp-as_360x180.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('52779885_768764123497269_101915150117765120_n.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('BunuOk.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('yes_honey.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('198577_1005036946766_2603460_n.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('vcDNW72.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('happy.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('goblin.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('gottem.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('lookign.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('suppe.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('owo.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('rape.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('dead_bird.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('EJJYNY-X0AIOXUX.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('Eternatus_Eternamax.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('a9EXGEDW_700w_0.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('853.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('chadgenie.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('a5j5xQ09_700w_0.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('a76DRNnE_700w_0.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('flat,550x550,075,f.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('DORIME.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('tumblr_n5clb0xhdg1ril7tio2_', 'MemeVisual');540.png
INSERT INTO votable(filename, type) VALUES ('HjalteBirmingham.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('nutt.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('aKVLMYbj_700w_0.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('gfhhklæoihygdhjkl.PNG', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('dfghyjuiuytyui.PNG', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('annz3zkZ_700w_0.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('aP7GZZ96_700w_0.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('aex4gebA_700w_0.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('785.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('giphy-downsized-medium.g', 'MemeVisual');if
INSERT INTO votable(filename, type) VALUES ('cursed-cakes13.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('87151187_191202665461415_1073532641912815616_n.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('IMG_20201001_220857.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('Screenshot_20200929-163710__01.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('IMG_20200710_231645.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('hjalte.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('Snapchat-944946711.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('37564178_10156564821949154_6119577030926270464_n.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('awakebutatwhatcost.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('JPEG_20190329_193052.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('image0 (1).jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('bazinga.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('17029084_1340807832607344_2114107161_n.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('52898405_327912334521846_8673880625448484864_n.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('bApNPod.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('maxresdefault.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('19800922_883948385101689_509596865743331509_o.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('61903308_306990690248536_1153569756905734144_n.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('62369978_445857866164387_3781500987940798464_n.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('JPEG_20190119_150550.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('53510680_398113764317723_4352409966733164544_n.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('1296810480352087.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('chrome_2018-09-13_11-01-21.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('42194671_256436875076668_8314669605423415296_n.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('42124233_573288443074591_6963037405892837376_n.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('EwXlqZz.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('mqdefault.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('xJmZMtZ.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('HAHA.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('42161694_297299800862672_4345910263875108864_n.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('9IyBWmaxresdefault.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('linusstare_highres.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('deepfry - Kopi.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('ColorfulLimpAlpineroadguidetigerbeetle-size_restricted.gif', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('675007723049582602.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('gordon.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('ebin meme.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('bb6.gif', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('slight_left.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('dan_witzner_hansen.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('download.jpg', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('Claus-Brabrand-small.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('2019-06-10_18.41.03.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('nl0Ji70.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('xhoakUntitled.png', 'MemeVisual');
INSERT INTO votable(filename, type) VALUES ('IMG_20201020_143208.jpg', 'MemeVisual');

INSERT INTO votable(filename, type) VALUES ('untitled.mp3', 'MemeSound');